name: dartcoin
version: 0.0.0
author: Steven Roose <stevenroose@gmail.com>
description: A Bitcoin library for Dart. Pub-test release.
homepage: http://www.dartcoin.org/
dependencies:
  bignum: '>=0.0.4'
  cipher:
    path: /home/steven/git/cipher
  cryptoutils: '>=0.1.8'
  collection: any
  crypto: any
  json: any
  json_rpc: any
  asn1lib: '>=0.3.1'
dev_dependencies:
  browser: any
  unittest: any
  uuid: any
